language: python

python:
  - "2.7"

sudo: required

dist: trusty

install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install texttest
  - pip install CaptureMock

script:
  - ls -al
  - ls -la .git
  - cat .git/config
  - ./test.sh
  - texttest -a gocdpb -b -c /home/travis/build/magnus-lycka/gocd-pipeline-builder -d /home/travis/build/magnus-lycka/gocd-pipeline-builder/src/texttest -l
  - find ~/.texttest/tmp -name 'std*.gocdpb' | xargs more | cat
  - find ~/.texttest/tmp -name 'pythonmocks.gocdpb' | xargs more | cat
